---
apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  name: {{ template "srsmilter.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
      {{- include "srsmilter.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  {{- if ne .Values.service.type "ClusterIP" }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}

  ports:
    - name: milter
      protocol: TCP
      port: 10382
      targetPort: 10382
    - name: socket
      protocol: TCP
      port: 10383
      targetPort: 10383
